# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322f8c489951b7026f21d022e1605d347c381cd695202ddfdef9f008b31524ed2c2fe77ff7fd48c80e87846047634fbe57d2a355516ee84e8e627b0edfa5c2d8

test:
  secret_key_base: f1faa8fdede14c61a4f9053b5884065d0663e42565c8d10b657e07cbb890a86624a25a8d6b8f62f939b74165ef666d05b44f9e685ddaf4e1343800652fe6ef74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 322f8c489951b7026f21d022e1605d347c381cd695202ddfdef9f008b31524ed2c2fe77ff7fd48c80e87846047634fbe57d2a355516ee84e8e627b0edfa5c2d8
